<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class MaterialsTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::table('materials')->insert([
            [
                'title' => 'Cuero negro',
                'customer_id' => 7,
                'description' => 'Cuero de alta calidad',
                'color' => '#000000',
                'unit_of_measure' => 'Metros',
                'stock' => 10.50,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Sintético blanco',
                'customer_id' => 5,
                'description' => 'Material sintético duradero',
                'color' => '#ffffff',
                'unit_of_measure' => 'Metros',
                'stock' => 8.75,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Biocuero marrón',
                'customer_id' => 3,
                'description' => 'Material ecológico resistente',
                'color' => '#8B4513',
                'unit_of_measure' => 'Metros',
                'stock' => 12.25,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Textil azul',
                'customer_id' => 8,
                'description' => 'Textil transpirable',
                'color' => '#0000ff',
                'unit_of_measure' => 'Metros',
                'stock' => 15.75,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Cuero marrón',
                'customer_id' => 9,
                'description' => 'Cuero clásico para calzado',
                'color' => '#8B4513',
                'unit_of_measure' => 'Metros',
                'stock' => 7.80,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Sintético rojo',
                'customer_id' => 4,
                'description' => 'Material sintético vibrante',
                'color' => '#ff0000',
                'unit_of_measure' => 'Metros',
                'stock' => 9.30,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Biocuero verde',
                'customer_id' => 2,
                'description' => 'Material ecológico en tono verde',
                'color' => '#008000',
                'unit_of_measure' => 'Metros',
                'stock' => 11.00,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Textil gris',
                'customer_id' => 6,
                'description' => 'Textil moderno y versátil',
                'color' => '#808080',
                'unit_of_measure' => 'Metros',
                'stock' => 14.20,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Cuero blanco',
                'customer_id' => 1,
                'description' => 'Cuero elegante para diseños frescos',
                'color' => '#ffffff',
                'unit_of_measure' => 'Metros',
                'stock' => 6.50,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Sintético negro',
                'customer_id' => 10,
                'description' => 'Material sintético clásico',
                'color' => '#000000',
                'unit_of_measure' => 'Metros',
                'stock' => 8.00,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Biocuero azul',
                'customer_id' => 7,
                'description' => 'Material ecológico en tono azul',
                'color' => '#0000ff',
                'unit_of_measure' => 'Metros',
                'stock' => 10.80,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Textil marrón',
                'customer_id' => 5,
                'description' => 'Textil resistente y de calidad',
                'color' => '#8B4513',
                'unit_of_measure' => 'Metros',
                'stock' => 13.50,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Cuero verde',
                'customer_id' => 3,
                'description' => 'Cuero de alta calidad en verde',
                'color' => '#008000',
                'unit_of_measure' => 'Metros',
                'stock' => 7.00,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Sintético azul',
                'customer_id' => 8,
                'description' => 'Material sintético en tono azul',
                'color' => '#0000ff',
                'unit_of_measure' => 'Metros',
                'stock' => 9.90,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Biocuero rojo',
                'customer_id' => 6,
                'description' => 'Material ecológico en tono rojo',
                'color' => '#ff0000',
                'unit_of_measure' => 'Metros',
                'stock' => 11.70,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Horma Botín #H156',
                'customer_id' => 5,
                'description' => 'Horma de botín para patronaje',
                'color' => '#808080',
                'unit_of_measure' => 'Unidades',
                'stock' => 15,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Horma Tacón Alto #TH42',
                'customer_id' => 3,
                'description' => 'Horma de tacón alto para patronaje y sereado',
                'color' => '#ff0000',
                'unit_of_measure' => 'Unidades',
                'stock' => 12,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Horma Plana #P78',
                'customer_id' => 7,
                'description' => 'Horma plana para patronaje y sereado',
                'color' => '#000000',
                'unit_of_measure' => 'Unidades',
                'stock' => 20,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Horma Deportiva #D94',
                'customer_id' => 2,
                'description' => 'Horma deportiva para patronaje y sereado',
                'color' => '#0000ff',
                'unit_of_measure' => 'Unidades',
                'stock' => 18,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Horma Sandalia #S32',
                'customer_id' => 6,
                'description' => 'Horma de sandalia para patronaje y sereado',
                'color' => '#ffff00',
                'unit_of_measure' => 'Unidades',
                'stock' => 10,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Horma Bota #B210',
                'customer_id' => 1,
                'description' => 'Horma de bota para patronaje y sereado',
                'color' => '#8B4513',
                'unit_of_measure' => 'Unidades',
                'stock' => 14,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Horma Oxford #O17',
                'customer_id' => 4,
                'description' => 'Horma de oxford para patronaje',
                'color' => '#ffffff',
                'unit_of_measure' => 'Unidades',
                'stock' => 16,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Horma Mocasín #M63',
                'customer_id' => 8,
                'description' => 'Horma de mocasín para patronaje y sereado',
                'color' => '#008000',
                'unit_of_measure' => 'Unidades',
                'stock' => 22,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Horma Sneaker #SN81',
                'customer_id' => 9,
                'description' => 'Horma de sneaker para patronaje y sereado',
                'color' => '#ff00ff',
                'unit_of_measure' => 'Unidades',
                'stock' => 25,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Horma Bailarina #B52',
                'customer_id' => 10,
                'description' => 'Horma de bailarina para patronaje y sereado',
                'color' => '#ffcc00',
                'unit_of_measure' => 'Unidades',
                'stock' => 13,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Capellada Bota Cuero Negro',
                'customer_id' => 5,
                'description' => 'Capelladas de cuero negro para botas',
                'color' => '#000000',
                'unit_of_measure' => 'Docenas',
                'stock' => 8,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Capellada Botín Sintético Marrón',
                'customer_id' => 3,
                'description' => 'Capelladas sintéticas marrones para botines',
                'color' => '#8B4513',
                'unit_of_measure' => 'Docenas',
                'stock' => 10,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Capellada Zapato Tacón Alto Rojo',
                'customer_id' => 7,
                'description' => 'Capelladas de tacón alto rojas para zapatos',
                'color' => '#ff0000',
                'unit_of_measure' => 'Docenas',
                'stock' => 12,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Capellada Sneaker Textil Azul',
                'customer_id' => 2,
                'description' => 'Capelladas de textil azul para sneakers',
                'color' => '#0000ff',
                'unit_of_measure' => 'Docenas',
                'stock' => 15,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Capellada Balerina Cuero Blanco',
                'customer_id' => 6,
                'description' => 'Capelladas de cuero blanco para ballerinas',
                'color' => '#ffffff',
                'unit_of_measure' => 'Docenas',
                'stock' => 9,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Capellada Mocasín Sintético Negro',
                'customer_id' => 1,
                'description' => 'Capelladas sintéticas negras para mocasines',
                'color' => '#000000',
                'unit_of_measure' => 'Docenas',
                'stock' => 11,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Capellada Bota Deportiva Verde',
                'customer_id' => 4,
                'description' => 'Capelladas deportivas verdes para botas',
                'color' => '#008000',
                'unit_of_measure' => 'Docenas',
                'stock' => 7,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Capellada Botín Cuero Marrón',
                'customer_id' => 8,
                'description' => 'Capelladas de cuero marrón para botines',
                'color' => '#8B4513',
                'unit_of_measure' => 'Docenas',
                'stock' => 13,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Capellada Oxford Textil Gris',
                'customer_id' => 9,
                'description' => 'Capelladas de textil gris para oxfords',
                'color' => '#808080',
                'unit_of_measure' => 'Docenas',
                'stock' => 14,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Capellada Sneaker Sintético Rosa',
                'customer_id' => 10,
                'description' => 'Capelladas sintéticas rosas para sneakers',
                'color' => '#ff00ff',
                'unit_of_measure' => 'Docenas',
                'stock' => 10,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Polibadana Beige',
                'customer_id' => 5,
                'description' => 'Polibadana para troquelado en color beige',
                'color' => '#f5f5dc',
                'unit_of_measure' => 'Metros',
                'stock' => 50.00,
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ]);
    }
}
